# Generated by Django 2.2.5 on 2019-10-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191019_0015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie_Links',
            new_name='MovieLinks',
        ),
    ]
