# Generated by Django 2.2.5 on 2019-10-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20191019_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'ROMANCE'), ('romance', 'ROMANCE')], max_length=1),
        ),
    ]
