# Generated by Django 2.2.5 on 2019-10-21 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 21, 21, 35, 14, 826018, tzinfo=utc)),
        ),
    ]
